title: Endika
description: "Endika Iglesias notes"
url: "http://endika.github.io"
twitter_username: endika_iglesias
github_username:  Endika
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
